name: progress_soft_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  flutter_bloc: ^8.1.6
  google_fonts: ^5.1.0
  rx_shared_preferences: ^3.1.0
  flutter_datetime_picker_plus: ^2.0.0+1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.5
  pinput: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.4.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
